name = "KamelCraft"
author = "Blackfur"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "277682d317444e42bcbbcacf99b74e1d66dca7e30b92e08d67e7a5b2f997380d"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
