name = "KamelCraft"
author = "Blackfur"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2500b744f8316543b08c037ff125ef47a4acb3fc7138cd51fe93511236d53f2"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
